# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
xcode_sdk: iphonesimulator10.1
script:
- set -o pipefail
- travis_retry xcodebuild -workspace Example/cuid.xcworkspace -scheme "cuid-Example" -destination "platform=iOS Simulator,name=iPhone 8" build-for-testing test | xcpretty